# Generated by Django 4.2.7 on 2023-11-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='metadata',
        ),
        migrations.AddField(
            model_name='logentry',
            name='parentResourceId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='commit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='resourceId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='spanId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='traceId',
            field=models.CharField(max_length=255),
        ),
    ]
